// Showcase span creation with the tracer interface.

POST http://localhost:8081/demo/tracer
Content-Type: application/json

{
  "userName": "apple",
  "groupName": ""
}

###

// Showcase span modification on the current span with the tracer interface.

POST http://localhost:8081/demo/tracer/current-span
Content-Type: application/json

{
  "userName": "apple",
  "groupName": ""
}

###

// Showcase span creation with NewSpan on a service method.

POST http://localhost:8081/demo/new-span
Content-Type: application/json

{
  "userName": "apple9",
  "groupName": ""
}

###

// Showcase span creation with NewSpan on an interface method.

GET http://localhost:8081/demo/new-span/repository/apple8
Accept: application/json

###
