// Important: You need a user for file creation.
POST http://localhost:8091/demo/tracer
Content-Type: application/json

{
  "userName": "apple"
}

###

// Showcase observation API.

POST http://localhost:8091/demo/observation
Content-Type: application/json

{
  "fileName": "test",
  "userName": "apple",
  "groupName": "apple",
  "userPermissions": "rw",
  "groupPermissions": "rw",
  "otherPermissions": ""
}

###

// Showcase observation API with manual scope.

POST http://localhost:8091/demo/observation-scope
Content-Type: application/json

{
  "fileName": "test2",
  "userName": "apple",
  "groupName": "apple",
  "userPermissions": "rw",
  "groupPermissions": "rw",
  "otherPermissions": ""
}

###

// Showcase observation API with convention and context

POST http://localhost:8091/demo/observation/convention
Content-Type: application/json

{
  "fileName": "test3",
  "userName": "apple",
  "groupName": "apple",
  "userPermissions": "rw",
  "groupPermissions": "rw",
  "otherPermissions": ""
}

###

// Showcase observation API with an overriden convention + context

POST http://localhost:8091/demo/observation/custom-convention
Content-Type: application/json

{
  "fileName": "test4",
  "userName": "apple",
  "groupName": "apple",
  "userPermissions": "rw",
  "groupPermissions": "rw",
  "otherPermissions": ""
}

###

// {{
// Showcase observation predicate ignoring observations for the user 'logger'.

// Create a 'logger' user
POST http://localhost:8091/demo/tracer
Content-Type: application/json

{
  "userName": "logger"
}

###

// Create a file with the logger user. No observation should be visible in Grafana.

POST http://localhost:8091/demo/observation/convention
Content-Type: application/json

{
  "fileName": "test5",
  "userName": "logger",
  "groupName": "logger",
  "userPermissions": "rw",
  "groupPermissions": "rw",
  "otherPermissions": ""
}

###

// }}

###

// Showcase observation documentation

POST http://localhost:8091/demo/observation-documentation
Content-Type: application/json

{
  "fileName": "test6",
  "userName": "apple",
  "groupName": "apple",
  "userPermissions": "rw",
  "groupPermissions": "rw",
  "otherPermissions": ""
}
